<?php
/*
Plugin Name: Custom Search Plugin
*/

function custom_search_plugin()
{
    global $wpdb;
	$template_directory = get_template_directory_uri();//get_template_directory();
	?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Patua+One&display=swap" rel="stylesheet">
<style>
/*font-family: 'Conv_BERNIERRegular-Regular', Raleway, Helvetica, Arial, Lucida, sans-serif;*/
/** Generated by FG **/
@font-face {
	font-family: 'Conv_BERNIERRegular-Regular';
	src: url('https://wrightbev.com/wp-content/themes/Divi-child/fonts/BERNIERRegular-Regular.eot');
	src: local('☺'), url('https://wrightbev.com/wp-content/themes/Divi-child/fonts/BERNIERRegular-Regular.woff') format('woff'), url('https://wrightbev.com/wp-content/themes/Divi-child/fonts/BERNIERRegular-Regular.ttf') format('truetype'), url('https://wrightbev.com/wp-content/themes/Divi-child/fonts/BERNIERRegular-Regular.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}
#widgets {
	margin-top: 5px;
	padding-bottom: 20px;
	display: none !important;
}
select {
	width: 144px;
}
input[type=text] {
	width: 144px;
	height: 22px;
}
.nav>li>a {
	padding: 0;
}
.et_right_sidebar #sidebar {
	display: none;
}
#left-area {
	width: 100%;
}
.et_right_sidebar #left-area {
	padding-right: 0;
}
.brands-images {
	border: 1px solid #1d3984;
	margin-bottom: 30px;
}
.brands-images button {
	margin: 0 auto;
	display: block;
	margin-bottom: 20px;
	border-width: 0;
	border-style: none;
	border-image: none;
	background-color: transparent;
	border: 1px solid #1d3984;
	text-decoration: none;
	padding: 5px 50px;
	border-radius: 5px;
	color:#1d3984;
}
.brands-images a {
	position: relative;
	display: block;
}
.page-container {
	padding-bottom: 0 !important;
}
#main-content .container {
	padding-top: 0;
}
.nav>li>a:hover {
	background-color: #1d3a84 !important;
}
#main-content .container:before {
	background-color: #fff;
}
.brands-images:hover {
	box-shadow: 0 8px 10px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
.brands-images:hover button {
	color: #fff;
	background-color: #1F3C82;
}
#main-content .container:before {
	display: none;
}
.banner {
	padding-top: 105px;
	padding-bottom: 105px;
	background-position: top center !important;
	background-size: cover !important;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	position: relative;
	overflow: hidden;
	margin-bottom: 30px;
}
.banner-text-bottom,.banner .content h2 {
	font-size: 80px;
	font-weight: 500;
	font-family: 'Patua One', cursive, Raleway, Helvetica, Arial, Lucida, sans-serif;
	text-align: center;
	color: #fff;
	
}
.banner-text-bottom h2{
	font-size: 60px;
	font-weight: 500;
	font-family: 'Patua One', cursive,Raleway, Helvetica, Arial, Lucida, sans-serif;
	text-align: left;
	color: #1d3984;
	
}
.banner .content p {
	font-family: 'Raleway', Helvetica, Arial, Lucida, sans-serif;
	font-size: 18px;
	text-align: center;
	color: #fff;
}
.banner-text-bottom p {
	font-family: 'Raleway', Helvetica, Arial, Lucida, sans-serif;
	font-size: 20px;
	text-align: left;
	color: #363636;
	font-weight:500;
}
div#left-area h1 {
	display: none;
}
.dote-imge {
    margin-top: -30px;
	margin-bottom:20px
}
.port_thumb_wrap {
    height: 320px;
}
@media only screen and (max-width: 960px) {
.banner-text-bottom h2 {
    font-size: 60px;}
	.banner-text-bottom, .banner .content h2{font-size:60px;}
	}
 @media only screen and (max-width: 768px) {
select {
	margin-bottom: 20px;
	width: 100%;
}
input[type=text] {
	width: 100%
}
.banner{padding:20px !important ;}

}
/* loader */
.loader {
	bottom: 0;
	left: 0;
	position: fixed;
	right: 0;
	text-align: center;
	top: 0;
	z-index: 44;
	background: rgba(0,0,0,.8);
	display: none;
}
.loader>.loadingTest {
	position: absolute;
	left: 50%;
	top: 50%;
	transform: translate(-50%, -50%);
	color: #fff;
	margin-top: 80px;
}
.loader>.uil-default-css {
	background: rgba(0,0,0,0);
	height: 200px;
	width: 200px;
	left: 50%;
	margin: -100px;
	position: absolute;
	top: 50%;
}
@-webkit-keyframes uil-default-anim {
0% {
opacity:1
}
100% {
opacity:0
}
}
@keyframes uil-default-anim {
0% {
opacity:1
}
100% {
opacity:0
}
}
.uil-default-css > div:nth-of-type(1) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: -0.5s;
	animation-delay: -0.5s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(2) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: -0.4128282828282828282828282867s;
	animation-delay: -0.4128282828282828282828282867s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(3) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: -0.33333333333333337s;
	animation-delay: -0.33333333333333337s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(4) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: -0.25s;
	animation-delay: -0.25s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(5) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: -0.12828282828282828282828282828289s;
	animation-delay: -0.12828282828282828282828282828289s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(6) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: -0.08333333333333331s;
	animation-delay: -0.08333333333333331s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(7) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: 0s;
	animation-delay: 0s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(8) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: 0.08333333333333337s;
	animation-delay: 0.08333333333333337s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(9) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: 0.12828282828282828282828282828283s;
	animation-delay: 0.12828282828282828282828282828283s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(10) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: 0.25s;
	animation-delay: 0.25s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(11) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: 0.33333333333333337s;
	animation-delay: 0.33333333333333337s;
}
.uil-default-css {
	position: relative;
	background: none;
	width: 200px;
	height: 200px;
}
.uil-default-css > div:nth-of-type(12) {
	-webkit-animation: uil-default-anim 1s linear infinite;
	animation: uil-default-anim 1s linear infinite;
	-webkit-animation-delay: 0.41282828282828282828282828663s;
	animation-delay: 0.41282828282828282828282828663s;
}
</style>
<script>
		// jQuery noConflict
	    $=jQuery.noConflict();
		// full width hero image
		$(window).load(function() {
	 
		/*	var x = jQuery('#banner-img').get(0).outerHTML;
			console.log(x);
			jQuery('#banner-img').remove();
			jQuery(x).insertAfter(jQuery("#main-content .container"));*/
		
			//jQuery(".loaded").fadeOut();
			//jQuery(".loader").delay(1000).fadeOut("slow");
			
			jQuery("#banner-img").insertBefore("#main-content .container");
			
		});
		
		
		$('.loader').show();
		//type fetching
		$(document).on('change', '#type', function() {
		  
		  $('.loader').show();
		  var type = $('#type').val();// Action goes here.
		  var category = $('#category').val();
		  //var sort_by = $('#sort_by').val();
		  var brand = $('#brand').val();
		  console.log(type);
		  
		  $.ajax({
						url:"<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php",	   
						type:'POST',
						//data:'action=custom_search&type='+type+'&category='+category+'&sort_by='+sort_by+'&brand='+brand,// + '&pid=' + $product,
						data:'action=custom_search&type='+type+'&category='+category+'&brand='+brand,						   
						success:function(results)
						{
							$("#resultarea").html('');	
							$("#resultarea").html(results);       
							//document.getElementById("productsListHolder").innerHTML=results;
							$('#resultarea').show();
							$('.loader').hide();
					    
						}
				});
		  
		});
		//category fetching
		$(document).on('change', '#category', function() {
		  $('.loader').show();
		  var type = $('#type').val();// Action goes here.
		  var category = $('#category').val();
		  //var sort_by = $('#sort_by').val();
		  var brand = $('#brand').val();
		  console.log(type);
		  
		  $.ajax({
						url:"<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php",	   
						type:'POST',
						//data:'action=custom_search&type='+type+'&category='+category+'&sort_by='+sort_by+'&brand='+brand,// + '&pid=' + $product,
						data:'action=custom_search&type='+type+'&category='+category+'&brand='+brand,						   
						success:function(results)
						{
							$("#resultarea").html('');	
							$("#resultarea").html(results);       
							//document.getElementById("productsListHolder").innerHTML=results;
							$('#resultarea').show();
					    	$('.loader').hide();
						}
				});
		  
		  
		});
		//category fetching
		/*$(document).on('change', '#sort_by', function() {
		  
		  var type = $('#type').val();// Action goes here.
		  var category = $('#category').val();
		  var sort_by = $('#sort_by').val();
		  var brand = $('#brand').val();
		 
		  
		  $.ajax({
						url:"<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php",	   
						type:'POST',
						data:'action=custom_search&type='+type+'&category='+category+'&sort_by='+sort_by+'&brand='+brand,// + '&pid=' + $product,
												   
						success:function(results)
						{
							$("#resultarea").html('');	
							$("#resultarea").html(results);       
							//document.getElementById("productsListHolder").innerHTML=results;
							$('#resultarea').show();
					    
						}
				});
		  
		});*/
		$(document).on('keyup','#brand',function () {
			$('.loader').show();
			var type = $('#type').val();// Action goes here.
		    var category = $('#category').val();
		    //var sort_by = $('#sort_by').val();
			var brand = $('#brand').val();
			console.log(brand);
			
			$.ajax({
						url:"<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php",	   
						type:'POST',
						//data:'action=custom_search&type='+type+'&category='+category+'&sort_by='+sort_by+'&brand='+brand,// + '&pid=' + $product,
						data:'action=custom_search&type='+type+'&category='+category+'&brand='+brand,						   
						success:function(results)
						{
							$("#resultarea").html('');	
							$("#resultarea").html(results);       
							//document.getElementById("productsListHolder").innerHTML=results;
							$('#resultarea').show();
							$('.loader').hide();
					    
						}
				});
		});
	</script>
<!-------banner html start------------>
<div id="banner-img">
<div class="banner img-responsive" style="background-image:url('https://wrightbev.com/wp-content/uploads/2018/12/Brand-Portfolio-Hero.jpg');">
  <div class="overlay"></div>
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <h2>Our Brand Portfolio</h2>
        <p>Carrying over 200 brands, explore all that we have to offer.</p>
      </div>
    </div>
  </div>
</div>
</div>

<div class="container">
<div class="banner-text-bottom">
  <div class="row">
    <div class="col-md-12">
      <h2>Partnerships That Span Generations</h2>
      <P>Wright Beverage has spent generations crafting a portfolio that strikes a balance
between classic cornerstone brands as well as items on the cutting edge of new trends in the
industry. With over 200 beer and cider brands, 50+ wineries and distilleries, and 50+ NA brands,
we are sure to be able to fulfill any customer’s beverage needs, no matter what the occasion. To
help navigate this plethora of brands, we also field a full-service sales force that can provide
insight and information on what mix of these brands is best for each customer.</P>
<div class="dote-imge">
<img src="https://wrightbev.com/wp-content/uploads/2018/12/Yellow-Dots.png" alt="#">
</div>
    </div>
  </div>
</div>
<!-------banner html end------------>
<div class="row">
  <div class="col-sm-3">
    <select id="type" class="styledSelect" name="type">
      <option value="">All Types</option>
      <option value="Alcohol">Alcohol</option>
      <option value="Non-Alcohol">Non-Alcohol</option>
    </select>
  </div>
  <div class="col-sm-3">
    <select id="category" class="styledSelect" name="category">
      <option value="">All Categories</option>
      <?php
	   $catNames = $wpdb->get_results("SELECT distinct category as category FROM website_brands");
	   foreach ( $catNames as $catNames ) 
			{
				echo '<option value="'.$catNames->category.'">'.$catNames->category.'</option>';
			}
	  ?>
    </select>
  </div>
  <div class="col-sm-6">
    <input type="text" name="brand" placeholder="Search Brands" value="" size="30" maxlength="30" id="brand" tabindex="3" />
  </div>
  <div class="loader">
    <div style="transform:scale(0.6);" class="uil-default-css">
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(0deg) translate(0,-60px);transform:rotate(0deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(30deg) translate(0,-60px);transform:rotate(30deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(60deg) translate(0,-60px);transform:rotate(60deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(90deg) translate(0,-60px);transform:rotate(90deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(120deg) translate(0,-60px);transform:rotate(120deg) translate(0,-60px);border-radius:10px;position:absolute;"> </div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(150deg) translate(0,-60px);transform:rotate(150deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(180deg) translate(0,-60px);transform:rotate(180deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(210deg) translate(0,-60px);transform:rotate(210deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(240deg) translate(0,-60px);transform:rotate(240deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(270deg) translate(0,-60px);transform:rotate(270deg) translate(0,-60px);border-radius:10px;position:absolute;"> </div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(300deg) translate(0,-60px);transform:rotate(300deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
      <div style="top:80px;left:93px;width:14px;height:40px;background:#b8f4f4;-webkit-transform:rotate(330deg) translate(0,-60px);transform:rotate(330deg) translate(0,-60px);border-radius:10px;position:absolute;"></div>
    </div>
  </div>
</div>
<div id="resultarea">
  <?php 
   $itemNames = $wpdb->get_results("SELECT * FROM website_brands order by brand asc");
   echo '<div class="row" style="margin-top:50px;text-align:center;color:#4CAF50;font-size:18x;"><span style="color:orange">'.count($itemNames).'  Records  found</span></div>';
	echo '<div class="row" style="margin-top: 50px;">';
	foreach ( $itemNames as $itemName ) 
			{
				$item_bid       = $itemName->bid;
				$supplier_link = $itemName->supplier_link;
				$logo_url       = $itemName->logo_url;
				
				echo '<div class="col-lg-3 col-md-2 col-sm-4 port_thumb_wrap">';
				echo '<div class="brands-images">';
				echo '<a href="https://'.$supplier_link.'" target="_blank">';
				echo '<img src="'.home_url().'/wp-content/brand_logo/'.$logo_url.'" alt="'.$logo_url.'" />';
				echo '<div class="button-detail">';
				echo '<button type="button01">Details</button>';
				echo '</div>';
				echo '</a>';
				echo '</div>';
				echo '</div>';
			}
	echo ' </div>';			?>
</div>
</div>
<?php	
}
add_shortcode('search_dd','custom_search_plugin');

function custom_search(){
	
	//echo "<pre>";print_r($_POST);
	global $wpdb;
	$template_directory = get_template_directory_uri();
	$type 	  = $_POST['type'];
	$category = $_POST['category'];
	//$sort_by  = $_POST['sort_by'];
	$brand    = $_POST['brand'];
	
	$condition = " WHERE ";
	$order_by = "";
	//1 all field fill
	if($type != "" && $category != "" && $brand !=""){
		
		$condition .= " type='{$type}' AND category='{$category}' AND brand LIKE '%".$brand."%'";
	}
	//2 type and category field fill
	else if($type != "" && $category != "" && $brand == ""){
		
		$condition .= " type='{$type}' AND category='{$category}'";
	}
	//3 type and brand field fill
	else if($type != "" && $category == "" && $brand !=""){
		
		$condition .= " type='{$type}' AND brand LIKE '%".$brand."%'";
	}
	//4 category and brand field fill
	else if($type == "" && $category != ""  && $brand !=""){
		
		$condition .= "  category='{$category}' AND brand LIKE '%".$brand."%'";
	}
	//5 type 
	else if($type != "" && $category == ""  && $brand =="" ){
		
		$condition .= " type='{$type}'";
	}
	//6 category
	else if($type == "" && $category != ""  && $brand =="" ){
		
		$condition .= " category='{$category}'";
	}
	//7 brand
	else if($type == "" && $category == ""  && $brand !="" ){
		
		$condition .= " brand LIKE '%".$brand."%'";
	}
	//8 all blank
	else if($type == "" && $category == ""  && $brand ==""){
		
		$condition = "";
	}
	// 9 sort by 
	//if($sort_by != ""){
		
		$order_by = " order by brand asc";
	//}
	//$condition .= " )";
	//echo "$condition $order_by";
	$itemNames = $wpdb->get_results("SELECT * FROM website_brands $condition $order_by");
	//echo "<pre>";print_r($itemNames);
	echo '<div class="row" style="margin-top:50px;text-align:center;color:#4CAF50;font-size:18px;"><span style="color:orange">'.count($itemNames).'   Records found</span></div>';
	echo '<div class="row" style="margin-top: 50px;">';
	foreach ( $itemNames as $itemName ) 
			{
				$item_bid       = $itemName->bid;
				$supplier_link = $itemName->supplier_link;
				$logo_url       = $itemName->logo_url;
				
				echo '<div class="col-lg-3 col-md-2 col-sm-4 port_thumb_wrap">';
				echo '<div class="brands-images">';
				echo '<a href="https://'.$supplier_link.'" target="_blank">';
				echo '<img src="'.home_url().'/wp-content/brand_logo/'.$logo_url.'" alt="'.$logo_url.'" />';
				echo '<div class="button-detail">';
				echo '<button type="button01">Details</button>';
				echo '</div>';
				echo '</a>';
				echo '</div>';
				echo '</div>';
			}
	echo ' </div>';
	exit;
}
add_action('wp_ajax_custom_search', 'custom_search');
add_action('wp_ajax_nopriv_custom_search', 'custom_search');

function test(){
  echo '<div class="et_pb_section et_pb_section_1 et_section_regular">	
<div class="et_pb_row et_pb_row_1">
<div class="et_pb_column et_pb_column_4_4 et_pb_column_1 et_pb_css_mix_blend_mode_passthrough et-last-child">
<div class="et_pb_module et_pb_text et_pb_text_2 et_pb_bg_layout_light et_pb_text_align_left">
<div class="et_pb_text_inner">
123
</div>
</div> <!-- .et_pb_text --><div class="et_pb_module et_pb_code et_pb_code_0">
<div class="et_pb_code_inner">
</div> <!-- .et_pb_code_inner -->
</div> <!-- .et_pb_code -->
</div> <!-- .et_pb_column -->
</div> <!-- .et_pb_row -->
</div>';
}
add_shortcode('test_dd','test');	

add_action( 'admin_menu', 'my_admin_menu' );

function my_admin_menu() {
	add_menu_page( 'Portfolio Page', 'Portfolio', 'manage_options', 'portfolio', 'portfolio', 'dashicons-tickets', 12  );
	add_submenu_page('portfolio', 'Portfolio Page', 'Add Portfolio', 'manage_options', 'add_portfolio', 'add_portfolio' ); 
	add_submenu_page( 'portfolio', 'Edit Portfolio', 'Edit Portfolio','manage_options', 'edit_portfolio', 'edit_portfolio');
	
}


function portfolio(){?>
	<div class="wrap">
		<h2>Portfolio Page Listing</h2>
	</div>
	<?php
	include_once("portfolio.php");
	
}

function add_portfolio(){?>
	<div class="wrap">
		<h2>Add portfolio Page</h2>
	</div>
	<?php
	include_once("add_portfolio.php");
	
}
function edit_portfolio(){?>
	<div class="wrap">
		<h2>Edit portfolio Page</h2>
	</div>
	<?php
	//echo "<pre>";print_r($_GET);
	include_once("edit_portfolio.php");
	
}
function delete_portfolio(){?>
	<div class="wrap">
		<h2>Edit portfolio Page</h2>
	</div>
	<?php
	include_once("delete_portfolio.php");
	
}

?>
